service: ftf-engine
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  environment:
    FTF_TABLE: ftf_engine
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ftfEngine, Arn ]
            - Fn::Join: ["/", [Fn::GetAtt: [ftfEngine, Arn], "index/*"]]


functions:
  createTruck:
    handler: handler.create_truck
    events:
      - httpApi:
          path: /trucks
          method: post
  getTrucks:
    handler: handler.get_trucks
    events:
      - httpApi:
          path: /trucks
          method: get


resources:
  Resources:
    ftfEngine:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ftf_engine
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: GSI1PK
            AttributeType: S
          - AttributeName: GSI1SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: GSI1PK
                KeyType: HASH
              - AttributeName: GSI1SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
plugins:
  - serverless-python-requirements
